### ISSUE TITLE
12月28日起好像用不了这个工具了啊，能麻烦作者试着修复一下吗？万分感谢！

### ISSUE THREAD

**Issue by WeedyGoldfish76** [TMYTiMidlY/capture-courses#13]

**Comment by lkbrain** [comment]
同为天涯沦落人 考完试回来听录课发现天塌了 :(

**Comment by naive-wcx** [comment]
同，但我发现似乎只是把列表关了，实际上过往的录课如果点开过的话是还能看的

**Comment by WeedyGoldfish76** [comment]
怎么说哥们

**Comment by lkbrain** [comment]
那些应该是老师本来就打开了录播的，但是公开录播课里的就看不了了吧、

**Comment by WeedyGoldfish76** [comment]
还真看得了，看起来只要这段编号有就可以看
<img width="716" alt="image" src="https://github.com/user-attachments/assets/9bf28d19-b145-49ec-84b6-ed746ed0ef2c" />

**Comment by lkbrain** [comment]
这段编码怎么获得哦

**Comment by WeedyGoldfish76** [comment]
这就是问题啊

**Comment by naive-wcx** [comment]
应该是 md5 编码，没办法逆向解密，我试了几个在线的数据库也没找到可能的原始编码形式

**Comment by lkbrain** [comment]
我看了报错，应该是学校新加了一个subCode，导致现在脚本解析出来的参数少了一个

**Comment by WeedyGoldfish76** [comment]
那哥们这还能有解决的办法吗

**Comment by Thebunniest** [comment]
诚心求作者大大解决一下🙏🙏🙏

**Comment by Su-Banxia** [comment]
一觉醒来天塌了

**Comment by LetMeSleeeeeeep** [comment]
下学期不得不叠课，但是被叠的那门课不公开录播，12月29日中午1点尝试失败了，作者大大加油啊（大哭/可怜）

**Comment by wzyustc** [comment]
> 下学期不得不叠课，但是被叠的那门课不公开录播，12月29日中午1点尝试失败了，作者大大加油啊（大哭/可怜）

作者更新了，目前尝试了下，可以用的

**Comment by TMYTiMidlY** [comment]
覆写文件现已更新，但目前仅支持完整的课程号搜索，详见README。谢谢大家的关注，还请注意不要将录课网站的视频上传至公共平台，也不要过分依赖录课网站破解工具。

**Comment by TMYTiMidlY** [comment]
> 应该是 md5 编码，没办法逆向解密，我试了几个在线的数据库也没找到可能的原始编码形式

@naive-wcx 事实上好像并不需要逆向解密，录课网站后端暴露了很多未受保护的API，可以直接得到这个编码。这也是我们这个工具脆弱的原因，一旦网站为这些API设置了权限或进行了加密，就只能用其他更高级的手段破解了。

**Comment by lkbrain** [comment]
作者大大万岁！

**Comment by ghost** [comment]
好像又不行了?

**Comment by TMYTiMidlY** [comment]
> 好像又不行了?

@TZSXFJH 我刚刚测试了一下，没有问题吧

**Comment by KosmosX17** [comment]
确实修复好了，谢谢作者大大！

ps.听说网站更新是因为有人把助教拳的录课给发知乎上了，难绷。

**Comment by ghost** [comment]
> > 好像又不行了?
> 
> @TZSXFJH 我刚刚测试了一下，没有问题吧

为啥我这里会这样, 返回NAN
![image](https://github.com/user-attachments/assets/49410058-7c53-4395-8f8c-af6de51b3e34)

**Comment by TMYTiMidlY** [comment]
> > > 好像又不行了?
> > 
> > 
> > @TZSXFJH 我刚刚测试了一下，没有问题吧
> 
> 为啥我这里会这样, 返回NAN ![image](https://private-user-images.githubusercontent.com/108392111/399315978-49410058-7c53-4395-8f8c-af6de51b3e34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MDE3MjcsIm5iZiI6MTczNTYwMTQyNywicGF0aCI6Ii8xMDgzOTIxMTEvMzk5MzE1OTc4LTQ5NDEwMDU4LTdjNTMtNDM5NS04ZjhjLWFmNmRlNTFiM2UzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQyMzMwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MDkwODIyZjEyOWI2ZDk2MTkxNzM2YjU2MWJjYzM0MDliMmI5MmEzNTM0YzljMDVkY2Q0ZDI3MDMzMTU4ZDBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OcUNIKrUJsxXjqTb9Zksiv7lArIwf26xwfMw_I8pZJo)

@TZSXFJH 应该是在 [USTC 在线视频平台-直录播-录播课程](https://v.ustc.edu.cn/capture-course/) 搜索

**Comment by TMYTiMidlY** [comment]
> > > 好像又不行了?
> > 
> > 
> > @TZSXFJH 我刚刚测试了一下，没有问题吧
> 
> 为啥我这里会这样, 返回NAN ![image](https://private-user-images.githubusercontent.com/108392111/399315978-49410058-7c53-4395-8f8c-af6de51b3e34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MDE4NDgsIm5iZiI6MTczNTYwMTU0OCwicGF0aCI6Ii8xMDgzOTIxMTEvMzk5MzE1OTc4LTQ5NDEwMDU4LTdjNTMtNDM5NS04ZjhjLWFmNmRlNTFiM2UzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQyMzMyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzMyYTlkYThhNWRhN2M0ZWUzZDQ3MTNlODEzNTI1MDJjMWQ3MDYwZGQ1OTUyZTBjMzNlNmNiYTc5ODY5MzY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qkPzboIcK7wK_rBjnH9-P__WXL1k6xwD2qWiVNJ0Fjs)

我测试的时候是在 [USTC 在线视频平台-直录播-录播课程](https://v.ustc.edu.cn/capture-course/)搜索的，在这里搜索可能无法得到默认的学期信息，你可以手动指定24秋试试

**Comment by TMYTiMidlY** [comment]
> 确实修复好了，谢谢作者大大！
> 
> ps.听说网站更新是因为有人把助教拳的录课给发知乎上了，难绷。

@KosmosX17 应该是这个原因，我很早就在README里面加了声明，没想到还是有人干这种事。应该是先在科大一些群里面流传，后来才传到网上的。所有此类工具应该都加上这种声明，不然迟早得凉

**Comment by ghost** [comment]
> > > > 好像又不行了?
> > > 
> > > 
> > > @TZSXFJH 我刚刚测试了一下，没有问题吧
> > 
> > 
> > 为啥我这里会这样, 返回NAN ![image](https://private-user-images.githubusercontent.com/108392111/399315978-49410058-7c53-4395-8f8c-af6de51b3e34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MDE4NDgsIm5iZiI6MTczNTYwMTU0OCwicGF0aCI6Ii8xMDgzOTIxMTEvMzk5MzE1OTc4LTQ5NDEwMDU4LTdjNTMtNDM5NS04ZjhjLWFmNmRlNTFiM2UzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQyMzMyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzMyYTlkYThhNWRhN2M0ZWUzZDQ3MTNlODEzNTI1MDJjMWQ3MDYwZGQ1OTUyZTBjMzNlNmNiYTc5ODY5MzY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qkPzboIcK7wK_rBjnH9-P__WXL1k6xwD2qWiVNJ0Fjs)
> 
> 我测试的时候是在 [USTC 在线视频平台-直录播-录播课程](https://v.ustc.edu.cn/capture-course/)搜索的，在这里搜索可能无法得到默认的学期信息，你可以手动指定24秋试试

在这个页面就可以了, 感谢

**Comment by hicode002** [comment]
> > > > 好像又不行了?
> > > 
> > > 
> > > @TZSXFJH 我刚刚测试了一下，没有问题吧
> > 
> > 
> > 为啥我这里会这样, 返回NAN ![image](https://private-user-images.githubusercontent.com/108392111/399315978-49410058-7c53-4395-8f8c-af6de51b3e34.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU2MDE4NDgsIm5iZiI6MTczNTYwMTU0OCwicGF0aCI6Ii8xMDgzOTIxMTEvMzk5MzE1OTc4LTQ5NDEwMDU4LTdjNTMtNDM5NS04ZjhjLWFmNmRlNTFiM2UzNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIzMFQyMzMyMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzMyYTlkYThhNWRhN2M0ZWUzZDQ3MTNlODEzNTI1MDJjMWQ3MDYwZGQ1OTUyZTBjMzNlNmNiYTc5ODY5MzY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.qkPzboIcK7wK_rBjnH9-P__WXL1k6xwD2qWiVNJ0Fjs)
> 
> 我测试的时候是在 [USTC 在线视频平台-直录播-录播课程](https://v.ustc.edu.cn/capture-course/)搜索的，在这里搜索可能无法得到默认的学期信息，你可以手动指定24秋试试

现在又不好用了，搜索MARX1011.20 24秋无结果，报错

```

index-8e80cd51.js:17  TypeError: Cannot read properties of undefined (reading 'instructors')
    at V (Index-183e19b1.js:1:9707)
    at async Index-183e19b1.js:1:11919
```

**Comment by 1003544318** [comment]
貌似1.5又不行了QAQ

**Comment by TMYTiMidlY** [comment]
> 貌似1.5又不行了QAQ

@1003544318 有问题提一个新的issue吧，告诉我如何复现

**Comment by LetMeSleeeeeeep** [comment]
1月15日晚10点半，人已在家，没有使用eduroam（不知道有没有影响）。先进入直录播，选择公开录播课，搜索24春 PHYS4005.01，失败，打开开发人员工具，在保持搜索栏中内容不变的情况下刷新，失败，改尝试24秋 MARX1011.01，再次失败，不会是又不行了吧（汗流浃背）
